### PR TITLE
Expose tlsConfig so tat it can be set via NewBot

### LINKED ISSUE #12: Cannot set tlsConfig in external configFunc
I just tried using a modified version of this:

```go
	configFunc := func(b *Bot) {
		b.Server = server
		b.OriginalName = name
		b.User = name
		b.tlsConfig = tlsConfig
	}
```

It fails to compile because `tlsConfig` is not exported. Any reason why that is so?

### PR DESCRIPTION
**Pull request by mvdan**
Fixes #12

### CODE REVIEW

**Comment by mvdan** [comment]
gonna fix the conflicts I myself caused.

**Comment by mvdan** [comment]
Done.

**Comment by nickvanw** [comment]
@mvdan Instead of #14, can you give a look at #9? That should fix this issue, and add more improvements to the configuration options.

**Comment by mvdan** [comment]
Oh, hadn't seen that one. Sure.

**Pull request closed without merging**
