### PR TITLE
Redo config methods to be more sane

### PR DESCRIPTION
**Pull request by nickvanw**
Removes the wasted code around Classic, WithLogin, TLSWithLogin, etc. Two required params (a name and a server), and the rest are handled by config methods.

For #5 - what do you think @alaska

### CODE REVIEW

**Comment by alaska** [comment]
I think this is fine, but it almost seems like overkill compared to a config struct.  Given a struct with sensible defaults, you can just as easily do

```go
type Config struct {
    // required options
    server string
    name   string
    // optional params
    password  string
    user      string
    tlsConfig *tls.Config
}

type Bot struct {
   config Config
   //etc
}
```

And then, for init:

```go
ircx.New(ircx.Config{..})
```

Which seems just as easy and more straightforward.  Maybe? I dunno.  I think there are different preferences and paradigms.  I, personally, like breaking configs out into a struct with exported fields for most cases because then they're documented alongside everything else in a clear way, and you can't then provide a long string of (potentially conflicting) mutators to an init function.

With this method, you could conceivably do something like:

```go
b := New(l.Addr().String(), "test-bot", WithLogin("test-user", "test-password"), WithTLS(botConfig), WithLogin("foo", "bar"))
```

Which, I mean, isn't a big deal I guess, but It's confusing. What do you think?

**Comment by alaska** [comment]
The godoc generated from a well-commented struct is generally pretty good:

```
~/go/src/github.com/nickvanw/ircx$ godoc . Config
type Config struct {
    //REQUIRED
    Server       string //IRC server to connect to
    OriginalName string //The nick the bot will use
    //OPTIONAL
    User      string      //username (if using auth)
    Password  string      //password (if using auth)
    TlsConfig *tls.Config //tls.Config (to use TLS)
}
```

**Comment by nickvanw** [comment]
The more I think about it, the more you're right.

If you want to open a PR with that @alaska, I'll probably merge it over this.

**Comment by alaska** [comment]
Will do.

**Pull request closed without merging**
